# Generated by Django 5.1.1 on 2024-09-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
